### ISSUE TITLE
Randomness increases suspiciously rapidly

### ISSUE THREAD

**Issue by fortran77** [dashpay/paperwallet-old#7]
When I go to https://paper.dash.org/ from Google Chrome, the displayed percentage goes up rapidly with even very slight mouse movement. It's very unlikely that moving the mouse pointer just a few millimeters could provide so much randomness. I think the randomness algorithm is not working correctly.

In the attached image, the blue trail near the top left corner shows how little mouse movement was needed to make the percentage go up to 92.

![paper](https://cloud.githubusercontent.com/assets/6755457/14299626/6ad6f21c-fb40-11e5-9ff1-c4b5cf83dd15.png)

**Comment by evan82** [comment]
I just merged the pull request to revert the changes which caused this and reverted the site to a previous, safer version.

**Comment by evan82** [comment]
Well, @UdjinM6 caused it here https://github.com/dashpay/paper.dash.org/commit/4b2d50bc57fd8e1eb37949d2a8b639b95071945d and it was fixed here https://github.com/dashpay/paper.dash.org/pull/1/files. He was just trying to fix the ">100%" message and broke it. I'll put out an advisory about it

**Comment by fortran77** [comment]
Now https://paper.dash.org/ gives me no visible mouse trail at all. A few seconds after I click anywhere, the wallet addresses appear, nearly instantly.

All this is very different from the behavior of https://www.bitaddress.org/, where I have to move the mouse pointer quite a bit before 100% is reached.

**Comment by darkcoinproject** [comment]
I've been in the process of still fixing it, it's reverted to 5ddab0b now,
which should solve the problem.

**Comment by evan82** [comment]
Please direct any other issues to https://github.com/dashpay/paper.dash.org, this is the old repo. I'm deleting it now.
